//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ProtoBufSchema.proto
namespace org.apache.hadoop.hbase.rest.protobuf.generated
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Version")]
  public partial class Version : global::ProtoBuf.IExtensible
  {
    public Version() {}
    
    private string _stargateVersion = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"stargateVersion", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string stargateVersion
    {
      get { return _stargateVersion; }
      set { _stargateVersion = value; }
    }
    private string _jvmVersion = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"jvmVersion", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string jvmVersion
    {
      get { return _jvmVersion; }
      set { _jvmVersion = value; }
    }
    private string _osVersion = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"osVersion", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string osVersion
    {
      get { return _osVersion; }
      set { _osVersion = value; }
    }
    private string _serverVersion = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"serverVersion", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string serverVersion
    {
      get { return _serverVersion; }
      set { _serverVersion = value; }
    }
    private string _jerseyVersion = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"jerseyVersion", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string jerseyVersion
    {
      get { return _jerseyVersion; }
      set { _jerseyVersion = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"StorageClusterStatus")]
  public partial class StorageClusterStatus : global::ProtoBuf.IExtensible
  {
    public StorageClusterStatus() {}
    
    private readonly global::System.Collections.Generic.List<org.apache.hadoop.hbase.rest.protobuf.generated.StorageClusterStatus.Node> _liveNodes = new global::System.Collections.Generic.List<org.apache.hadoop.hbase.rest.protobuf.generated.StorageClusterStatus.Node>();
    [global::ProtoBuf.ProtoMember(1, Name=@"liveNodes", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<org.apache.hadoop.hbase.rest.protobuf.generated.StorageClusterStatus.Node> liveNodes
    {
      get { return _liveNodes; }
    }
  
    private readonly global::System.Collections.Generic.List<string> _deadNodes = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(2, Name=@"deadNodes", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> deadNodes
    {
      get { return _deadNodes; }
    }
  
    private int _regions = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"regions", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int regions
    {
      get { return _regions; }
      set { _regions = value; }
    }
    private int _requests = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"requests", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int requests
    {
      get { return _requests; }
      set { _requests = value; }
    }
    private double _averageLoad = default(double);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"averageLoad", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(double))]
    public double averageLoad
    {
      get { return _averageLoad; }
      set { _averageLoad = value; }
    }
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Region")]
  public partial class Region : global::ProtoBuf.IExtensible
  {
    public Region() {}
    
    private byte[] _name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] name
    {
      get { return _name; }
      set { _name = value; }
    }
    private int _stores = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"stores", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int stores
    {
      get { return _stores; }
      set { _stores = value; }
    }
    private int _storefiles = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"storefiles", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int storefiles
    {
      get { return _storefiles; }
      set { _storefiles = value; }
    }
    private int _storefileSizeMB = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"storefileSizeMB", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int storefileSizeMB
    {
      get { return _storefileSizeMB; }
      set { _storefileSizeMB = value; }
    }
    private int _memstoreSizeMB = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"memstoreSizeMB", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int memstoreSizeMB
    {
      get { return _memstoreSizeMB; }
      set { _memstoreSizeMB = value; }
    }
    private int _storefileIndexSizeMB = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"storefileIndexSizeMB", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int storefileIndexSizeMB
    {
      get { return _storefileIndexSizeMB; }
      set { _storefileIndexSizeMB = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Node")]
  public partial class Node : global::ProtoBuf.IExtensible
  {
    public Node() {}
    
    private string _name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private long _startCode = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"startCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long startCode
    {
      get { return _startCode; }
      set { _startCode = value; }
    }
    private int _requests = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"requests", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int requests
    {
      get { return _requests; }
      set { _requests = value; }
    }
    private int _heapSizeMB = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"heapSizeMB", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int heapSizeMB
    {
      get { return _heapSizeMB; }
      set { _heapSizeMB = value; }
    }
    private int _maxHeapSizeMB = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"maxHeapSizeMB", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int maxHeapSizeMB
    {
      get { return _maxHeapSizeMB; }
      set { _maxHeapSizeMB = value; }
    }
    private readonly global::System.Collections.Generic.List<org.apache.hadoop.hbase.rest.protobuf.generated.StorageClusterStatus.Region> _regions = new global::System.Collections.Generic.List<org.apache.hadoop.hbase.rest.protobuf.generated.StorageClusterStatus.Region>();
    [global::ProtoBuf.ProtoMember(6, Name=@"regions", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<org.apache.hadoop.hbase.rest.protobuf.generated.StorageClusterStatus.Region> regions
    {
      get { return _regions; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TableList")]
  public partial class TableList : global::ProtoBuf.IExtensible
  {
    public TableList() {}
    
    private readonly global::System.Collections.Generic.List<string> _name = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(1, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> name
    {
      get { return _name; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TableInfo")]
  public partial class TableInfo : global::ProtoBuf.IExtensible
  {
    public TableInfo() {}
    
    private string _name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private readonly global::System.Collections.Generic.List<org.apache.hadoop.hbase.rest.protobuf.generated.TableInfo.Region> _regions = new global::System.Collections.Generic.List<org.apache.hadoop.hbase.rest.protobuf.generated.TableInfo.Region>();
    [global::ProtoBuf.ProtoMember(2, Name=@"regions", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<org.apache.hadoop.hbase.rest.protobuf.generated.TableInfo.Region> regions
    {
      get { return _regions; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Region")]
  public partial class Region : global::ProtoBuf.IExtensible
  {
    public Region() {}
    
    private string _name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private byte[] _startKey = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"startKey", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] startKey
    {
      get { return _startKey; }
      set { _startKey = value; }
    }
    private byte[] _endKey = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"endKey", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] endKey
    {
      get { return _endKey; }
      set { _endKey = value; }
    }
    private long _id = default(long);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _location = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"location", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string location
    {
      get { return _location; }
      set { _location = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TableSchema")]
  public partial class TableSchema : global::ProtoBuf.IExtensible
  {
    public TableSchema() {}
    
    private string _name = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private readonly global::System.Collections.Generic.List<org.apache.hadoop.hbase.rest.protobuf.generated.TableSchema.Attribute> _attrs = new global::System.Collections.Generic.List<org.apache.hadoop.hbase.rest.protobuf.generated.TableSchema.Attribute>();
    [global::ProtoBuf.ProtoMember(2, Name=@"attrs", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<org.apache.hadoop.hbase.rest.protobuf.generated.TableSchema.Attribute> attrs
    {
      get { return _attrs; }
    }
  
    private readonly global::System.Collections.Generic.List<org.apache.hadoop.hbase.rest.protobuf.generated.ColumnSchema> _columns = new global::System.Collections.Generic.List<org.apache.hadoop.hbase.rest.protobuf.generated.ColumnSchema>();
    [global::ProtoBuf.ProtoMember(3, Name=@"columns", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<org.apache.hadoop.hbase.rest.protobuf.generated.ColumnSchema> columns
    {
      get { return _columns; }
    }
  
    private bool _inMemory = default(bool);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"inMemory", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool inMemory
    {
      get { return _inMemory; }
      set { _inMemory = value; }
    }
    private bool _readOnly = default(bool);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"readOnly", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool readOnly
    {
      get { return _readOnly; }
      set { _readOnly = value; }
    }
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Attribute")]
  public partial class Attribute : global::ProtoBuf.IExtensible
  {
    public Attribute() {}
    
    private string _name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private string _value;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string value
    {
      get { return _value; }
      set { _value = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ColumnSchema")]
  public partial class ColumnSchema : global::ProtoBuf.IExtensible
  {
    public ColumnSchema() {}
    
    private string _name = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private readonly global::System.Collections.Generic.List<org.apache.hadoop.hbase.rest.protobuf.generated.ColumnSchema.Attribute> _attrs = new global::System.Collections.Generic.List<org.apache.hadoop.hbase.rest.protobuf.generated.ColumnSchema.Attribute>();
    [global::ProtoBuf.ProtoMember(2, Name=@"attrs", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<org.apache.hadoop.hbase.rest.protobuf.generated.ColumnSchema.Attribute> attrs
    {
      get { return _attrs; }
    }
  
    private int _ttl = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"ttl", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ttl
    {
      get { return _ttl; }
      set { _ttl = value; }
    }
    private int _maxVersions = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"maxVersions", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int maxVersions
    {
      get { return _maxVersions; }
      set { _maxVersions = value; }
    }
    private string _compression = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"compression", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string compression
    {
      get { return _compression; }
      set { _compression = value; }
    }
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Attribute")]
  public partial class Attribute : global::ProtoBuf.IExtensible
  {
    public Attribute() {}
    
    private string _name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private string _value;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string value
    {
      get { return _value; }
      set { _value = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Cell")]
  public partial class Cell : global::ProtoBuf.IExtensible
  {
    public Cell() {}
    
    private byte[] _row = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"row", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] row
    {
      get { return _row; }
      set { _row = value; }
    }
    private byte[] _column = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"column", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] column
    {
      get { return _column; }
      set { _column = value; }
    }
    private long _timestamp = default(long);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"timestamp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long timestamp
    {
      get { return _timestamp; }
      set { _timestamp = value; }
    }
    private byte[] _data = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] data
    {
      get { return _data; }
      set { _data = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CellSet")]
  public partial class CellSet : global::ProtoBuf.IExtensible
  {
    public CellSet() {}
    
    private readonly global::System.Collections.Generic.List<org.apache.hadoop.hbase.rest.protobuf.generated.CellSet.Row> _rows = new global::System.Collections.Generic.List<org.apache.hadoop.hbase.rest.protobuf.generated.CellSet.Row>();
    [global::ProtoBuf.ProtoMember(1, Name=@"rows", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<org.apache.hadoop.hbase.rest.protobuf.generated.CellSet.Row> rows
    {
      get { return _rows; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Row")]
  public partial class Row : global::ProtoBuf.IExtensible
  {
    public Row() {}
    
    private byte[] _key;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"key", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] key
    {
      get { return _key; }
      set { _key = value; }
    }
    private readonly global::System.Collections.Generic.List<org.apache.hadoop.hbase.rest.protobuf.generated.Cell> _values = new global::System.Collections.Generic.List<org.apache.hadoop.hbase.rest.protobuf.generated.Cell>();
    [global::ProtoBuf.ProtoMember(2, Name=@"values", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<org.apache.hadoop.hbase.rest.protobuf.generated.Cell> values
    {
      get { return _values; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Scanner")]
  public partial class Scanner : global::ProtoBuf.IExtensible
  {
    public Scanner() {}
    
    private byte[] _startRow = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"startRow", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] startRow
    {
      get { return _startRow; }
      set { _startRow = value; }
    }
    private byte[] _endRow = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"endRow", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] endRow
    {
      get { return _endRow; }
      set { _endRow = value; }
    }
    private readonly global::System.Collections.Generic.List<byte[]> _columns = new global::System.Collections.Generic.List<byte[]>();
    [global::ProtoBuf.ProtoMember(3, Name=@"columns", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<byte[]> columns
    {
      get { return _columns; }
    }
  
    private int _batch = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"batch", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int batch
    {
      get { return _batch; }
      set { _batch = value; }
    }
    private long _startTime = default(long);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"startTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long startTime
    {
      get { return _startTime; }
      set { _startTime = value; }
    }
    private long _endTime = default(long);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"endTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long endTime
    {
      get { return _endTime; }
      set { _endTime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}